import { Router } from "express";
import { requireAuth } from "../middleware/auth.js";
import { adminRouter } from "../modules/admin/routes.js";
import { auditRouter } from "../modules/audit/routes.js";
import { authRouter } from "../modules/auth/routes.js";
import { catalogRouter } from "../modules/catalog/routes.js";
import { contentRouter } from "../modules/content/routes.js";
import { customersRouter } from "../modules/customers/routes.js";
import { dashboardRouter } from "../modules/dashboard/routes.js";
import { inventoryRouter } from "../modules/inventory/routes.js";
import { mediaRouter } from "../modules/media/routes.js";
import { notificationsRouter } from "../modules/notifications/routes.js";
import { ordersRouter } from "../modules/orders/routes.js";
import { paymentsRouter } from "../modules/payments/routes.js";
import { promotionsRouter } from "../modules/promotions/routes.js";
import { reportsRouter } from "../modules/reports/routes.js";
import { reviewsRouter } from "../modules/reviews/routes.js";
import { settingsRouter } from "../modules/settings/routes.js";
import { shippingRouter } from "../modules/shipping/routes.js";
import { storefrontRouter } from "../modules/storefront/routes.js";

export const apiRouter = Router();

apiRouter.use("/auth", authRouter);
apiRouter.use("/store", storefrontRouter);
apiRouter.use(requireAuth);
apiRouter.use("/dashboard", dashboardRouter);
apiRouter.use("/admin", adminRouter);
apiRouter.use("/catalog", catalogRouter);
apiRouter.use("/orders", ordersRouter);
apiRouter.use("/payments", paymentsRouter);
apiRouter.use("/customers", customersRouter);
apiRouter.use("/inventory", inventoryRouter);
apiRouter.use("/promotions", promotionsRouter);
apiRouter.use("/content", contentRouter);
apiRouter.use("/shipping", shippingRouter);
apiRouter.use("/reviews", reviewsRouter);
apiRouter.use("/reports", reportsRouter);
apiRouter.use("/settings", settingsRouter);
apiRouter.use("/notifications", notificationsRouter);
apiRouter.use("/media", mediaRouter);
apiRouter.use("/audit", auditRouter);
